from odoo import fields
from pytest_tr_odoo.fixtures import env
# from .test_account_move import partner

# Function _create_lines_wht

DATA_CREATE_LINES_WHT = {
    'seq_wht_1_date': '',
    'wht_total_base_amount': 0,
    'seq_wht_1_total_base_amount': 0,
    'seq_wht_1_base_amount': 0,
    'seq_wht_1_base_amount_precision': 0,
    'total_base_amount': 0,
    'wht_total_base_amount_precision': 0,
    'seq_wht_1_total_tax_amount': 0,
    'seq_wht_1_tax_amount': 0,
    'seq_wht_1_tax_amount_precision': 0,
    'wht_note_4_2_5': '',
    'list_wht_note_4_2_5': [],
    'wht_note_6': '',
    'list_wht_note_6': [],
    'wht_total_tax_amount': 0,
    'th_wht_total_tax_amount': '',
    'total_tax_amount': 0,
    'wht_total_tax_amount_precision': 0,
    'seq_wht_2_date': '',
    'seq_wht_2_total_base_amount': 0,
    'seq_wht_2_base_amount': 0,
    'seq_wht_2_base_amount_precision': 0,
    'seq_wht_2_total_tax_amount': 0,
    'seq_wht_2_tax_amount': 0,
    'seq_wht_2_tax_amount_precision': 0,
    'seq_wht_3_date': '',
    'seq_wht_3_total_base_amount': 0,
    'seq_wht_3_base_amount': 0,
    'seq_wht_3_base_amount_precision': 0,
    'seq_wht_3_total_tax_amount': 0,
    'seq_wht_3_tax_amount': 0,
    'seq_wht_3_tax_amount_precision': 0,
    'seq_wht_4_date': '',
    'seq_wht_4_total_base_amount': 0,
    'seq_wht_4_base_amount': 0,
    'seq_wht_4_base_amount_precision': 0,
    'seq_wht_4_total_tax_amount': 0,
    'seq_wht_4_tax_amount': 0,
    'seq_wht_4_tax_amount_precision': 0,
    'seq_wht_4_1_1_date': '',
    'seq_wht_4_1_1_total_base_amount': 0,
    'seq_wht_4_1_1_base_amount': 0,
    'seq_wht_4_1_1_base_amount_precision': 0,
    'seq_wht_4_1_1_total_tax_amount': 0,
    'seq_wht_4_1_1_tax_amount': 0,
    'seq_wht_4_1_1_tax_amount_precision': 0,
    'seq_wht_4_1_2_date': '',
    'seq_wht_4_1_2_total_base_amount': 0,
    'seq_wht_4_1_2_base_amount': 0,
    'seq_wht_4_1_2_base_amount_precision': 0,
    'seq_wht_4_1_2_total_tax_amount': 0,
    'seq_wht_4_1_2_tax_amount': 0,
    'seq_wht_4_1_2_tax_amount_precision': 0,
    'seq_wht_4_1_3_date': '',
    'seq_wht_4_1_3_total_base_amount': 0,
    'seq_wht_4_1_3_base_amount': 0,
    'seq_wht_4_1_3_base_amount_precision': 0,
    'seq_wht_4_1_3_total_tax_amount': 0,
    'seq_wht_4_1_3_tax_amount': 0,
    'seq_wht_4_1_3_tax_amount_precision': 0,
    'seq_wht_4_1_4_date': '',
    'seq_wht_4_1_4_total_base_amount': 0,
    'seq_wht_4_1_4_base_amount': 0,
    'seq_wht_4_1_4_base_amount_precision': 0,
    'seq_wht_4_1_4_total_tax_amount': 0,
    'seq_wht_4_1_4_tax_amount': 0,
    'seq_wht_4_1_4_tax_amount_precision': 0,
    'seq_wht_4_2_1_date': '',
    'seq_wht_4_2_1_total_base_amount': 0,
    'seq_wht_4_2_1_base_amount': 0,
    'seq_wht_4_2_1_base_amount_precision': 0,
    'seq_wht_4_2_1_total_tax_amount': 0,
    'seq_wht_4_2_1_tax_amount': 0,
    'seq_wht_4_2_1_tax_amount_precision': 0,
    'seq_wht_4_2_2_date': '',
    'seq_wht_4_2_2_total_base_amount': 0,
    'seq_wht_4_2_2_base_amount': 0,
    'seq_wht_4_2_2_base_amount_precision': 0,
    'seq_wht_4_2_2_total_tax_amount': 0,
    'seq_wht_4_2_2_tax_amount': 0,
    'seq_wht_4_2_2_tax_amount_precision': 0,
    'seq_wht_4_2_3_date': '',
    'seq_wht_4_2_3_total_base_amount': 0,
    'seq_wht_4_2_3_base_amount': 0,
    'seq_wht_4_2_3_base_amount_precision': 0,
    'seq_wht_4_2_3_total_tax_amount': 0,
    'seq_wht_4_2_3_tax_amount': 0,
    'seq_wht_4_2_3_tax_amount_precision': 0,
    'seq_wht_4_2_4_date': '',
    'seq_wht_4_2_4_total_base_amount': 0,
    'seq_wht_4_2_4_base_amount': 0,
    'seq_wht_4_2_4_base_amount_precision': 0,
    'seq_wht_4_2_4_total_tax_amount': 0,
    'seq_wht_4_2_4_tax_amount': 0,
    'seq_wht_4_2_4_tax_amount_precision': 0,
    'seq_wht_4_2_5_date': '',
    'seq_wht_4_2_5_total_base_amount': 0,
    'seq_wht_4_2_5_base_amount': 0,
    'seq_wht_4_2_5_base_amount_precision': 0,
    'seq_wht_4_2_5_total_tax_amount': 0,
    'seq_wht_4_2_5_tax_amount': 0,
    'seq_wht_4_2_5_tax_amount_precision': 0,
    'seq_wht_5_date': '',
    'seq_wht_5_total_base_amount': 0,
    'seq_wht_5_base_amount': 0,
    'seq_wht_5_base_amount_precision': 0,
    'seq_wht_5_total_tax_amount': 0,
    'seq_wht_5_tax_amount': 0,
    'seq_wht_5_tax_amount_precision': 0,
    'seq_wht_6_date': '',
    'seq_wht_6_total_base_amount': 0,
    'seq_wht_6_base_amount': 0,
    'seq_wht_6_base_amount_precision': 0,
    'seq_wht_6_total_tax_amount': 0,
    'seq_wht_6_tax_amount': 0,
    'seq_wht_6_tax_amount_precision': 0}

# Function prepare_lines_wht

DATAS_WHT_TYPE = [
    '1. เงินเดือน ค่าจ้าง เบี้ยเลี้ยง โบนัส ฯลฯ ตามมาตรา 40 (1)',
    '2. ค่าธรรมเนียม ค่านายหน้า ฯลฯ ตามมาตรา 40 (2)',
    '3. ค่าแห่งลิขสิทธิ์ ฯลฯ ตามมาตรา 40 (3)',
    '4 (ก) ดอกเบี้ย ฯลฯ ตามมาตรา 40 (4)(ก)',
    '4 (1.1) อัตราร้อยละ 30 ของกำไรสุทธิ ตามมาตรา 40 (4)(ข)',
    '4 (1.2) อัตราร้อยละ 25 ของกำไรสุทธิ ตามมาตรา 40 (4)(ข)',
    '4 (1.3) อัตราร้อยละ 20 ของกำไรสุทธิ ตามมาตรา 40 (4)(ข)',
    '4 (1.4) อัตราอื่นๆ ฯลฯ ตามมาตรา 40 (4)(ข)',
    '4 (2.1) กำไรสุทธิของกิจการที่ได้รับยกเว้นเงินได้ภาษีเงินได้นิติบุคคล',
    '4 (2.2) เงินปันผลหรือเงินส่วนแบ่งของกำไรที่ได้รับยกเว้นไม่ต้องนำมารวมคำนวณเป็นรายได้เพื่อเสียภาษีเงินได้นิติบุคคล',
    '4 (2.3) กำไรสุทธิส่วนที่ได้หักผลขาดทุนสุทธิยกมาไม่เกิน 5 ปีก่อนรอบระยะเวลาบัญชีปีปัจจุบัน',
    '4 (2.4) กำไรที่รับรู้ทางบัญชีโดยวิธีส่วนได้เสีย(Equity method)',
    '4 (2.5) อื่นๆ',
    '5.6 ค่าเบี้ยประกันวินาศภัย',
    '5.2 ค่าโฆษณา',
    '5 การจ่ายเงินได้ที่ต้องหักภาษี ณ ที่จ่าย ตามคำสั่งกรมสรรพากรที่ออกตามมาตรา 3 เตรส เช่น รางวัล ส่นลดหรือประโยชน์ใดๆ เนื่องากการส่งเสริมการขาย รางวัลในการประกวด การแข่งขัน การชิงโชค ค่าแสดงของนักแสดงสาธารณะ ค่าจ้าทำของ ค่าโฆษณา ค่าเช่า ค่าขนส่ง ค่าบริการ ค่า',
    '5.5 ค่าบริการ',
    '5.3 ค่าเช่า',
    '5.4  ค่าขนส่ง',
    '5.1 ค่าจ้างทำของ',
    '6 อื่นๆ(ระบุ)',
    '6.5 ค่าบริการ',
    '6.3 ค่าเช่า',
    '6.1 ค่าจ้างทำของ',
    '6.2 ค่าโฆษณา',
    '6.4  ค่าขนส่ง',
    '6.6 ค่าเบี้ยประกันวินาศภัย',
]


EXPECTED_PREPARE_LINES_WHT = {
    'seq_wht_1_date': '19/04/2565',
    'wht_total_base_amount': '81,000',
    'seq_wht_1_total_base_amount': 3000.0,
    'seq_wht_1_base_amount': '3,000',
    'seq_wht_1_base_amount_precision': '00',
    'total_base_amount': 81000.0,
    'wht_total_base_amount_precision': '00',
    'seq_wht_1_total_tax_amount': 300.0,
    'seq_wht_1_tax_amount': '300',
    'seq_wht_1_tax_amount_precision': '00',
    'wht_note_4_2_5': 'Account WHT',
    'list_wht_note_4_2_5': ['Account WHT'],
    'wht_note_6': 'Account WHT, Account WHT, Account WHT, Account WHT, Account WHT, Account WHT, Account WHT',
    'list_wht_note_6': [
        'Account WHT',
        'Account WHT',
        'Account WHT',
        'Account WHT',
        'Account WHT',
        'Account WHT',
        'Account WHT'],
    'wht_total_tax_amount': '8,100',
    'th_wht_total_tax_amount': 'แปดพันหนึ่งร้อยบาทถ้วน',
    'total_tax_amount': 8100.0,
    'wht_total_tax_amount_precision': '00',
    'seq_wht_2_date': '19/04/2565',
    'seq_wht_2_total_base_amount': 3000.0,
    'seq_wht_2_base_amount': '3,000',
    'seq_wht_2_base_amount_precision': '00',
    'seq_wht_2_total_tax_amount': 300.0,
    'seq_wht_2_tax_amount': '300',
    'seq_wht_2_tax_amount_precision': '00',
    'seq_wht_3_date': '19/04/2565',
    'seq_wht_3_total_base_amount': 3000.0,
    'seq_wht_3_base_amount': '3,000',
    'seq_wht_3_base_amount_precision': '00',
    'seq_wht_3_total_tax_amount': 300.0,
    'seq_wht_3_tax_amount': '300',
    'seq_wht_3_tax_amount_precision': '00',
    'seq_wht_4_date': '19/04/2565',
    'seq_wht_4_total_base_amount': 3000.0,
    'seq_wht_4_base_amount': '3,000',
    'seq_wht_4_base_amount_precision': '00',
    'seq_wht_4_total_tax_amount': 300.0,
    'seq_wht_4_tax_amount': '300',
    'seq_wht_4_tax_amount_precision': '00',
    'seq_wht_4_1_1_date': '19/04/2565',
    'seq_wht_4_1_1_total_base_amount': 3000.0,
    'seq_wht_4_1_1_base_amount': '3,000',
    'seq_wht_4_1_1_base_amount_precision': '00',
    'seq_wht_4_1_1_total_tax_amount': 300.0,
    'seq_wht_4_1_1_tax_amount': '300',
    'seq_wht_4_1_1_tax_amount_precision': '00',
    'seq_wht_4_1_2_date': '19/04/2565',
    'seq_wht_4_1_2_total_base_amount': 3000.0,
    'seq_wht_4_1_2_base_amount': '3,000',
    'seq_wht_4_1_2_base_amount_precision': '00',
    'seq_wht_4_1_2_total_tax_amount': 300.0,
    'seq_wht_4_1_2_tax_amount': '300',
    'seq_wht_4_1_2_tax_amount_precision': '00',
    'seq_wht_4_1_3_date': '19/04/2565',
    'seq_wht_4_1_3_total_base_amount': 3000.0,
    'seq_wht_4_1_3_base_amount': '3,000',
    'seq_wht_4_1_3_base_amount_precision': '00',
    'seq_wht_4_1_3_total_tax_amount': 300.0,
    'seq_wht_4_1_3_tax_amount': '300',
    'seq_wht_4_1_3_tax_amount_precision': '00',
    'seq_wht_4_1_4_date': '19/04/2565',
    'seq_wht_4_1_4_total_base_amount': 3000.0,
    'seq_wht_4_1_4_base_amount': '3,000',
    'seq_wht_4_1_4_base_amount_precision': '00',
    'seq_wht_4_1_4_total_tax_amount': 300.0,
    'seq_wht_4_1_4_tax_amount': '300',
    'seq_wht_4_1_4_tax_amount_precision': '00',
    'seq_wht_4_2_1_date': '19/04/2565',
    'seq_wht_4_2_1_total_base_amount': 3000.0,
    'seq_wht_4_2_1_base_amount': '3,000',
    'seq_wht_4_2_1_base_amount_precision': '00',
    'seq_wht_4_2_1_total_tax_amount': 300.0,
    'seq_wht_4_2_1_tax_amount': '300',
    'seq_wht_4_2_1_tax_amount_precision': '00',
    'seq_wht_4_2_2_date': '19/04/2565',
    'seq_wht_4_2_2_total_base_amount': 3000.0,
    'seq_wht_4_2_2_base_amount': '3,000',
    'seq_wht_4_2_2_base_amount_precision': '00',
    'seq_wht_4_2_2_total_tax_amount': 300.0,
    'seq_wht_4_2_2_tax_amount': '300',
    'seq_wht_4_2_2_tax_amount_precision': '00',
    'seq_wht_4_2_3_date': '19/04/2565',
    'seq_wht_4_2_3_total_base_amount': 3000.0,
    'seq_wht_4_2_3_base_amount': '3,000',
    'seq_wht_4_2_3_base_amount_precision': '00',
    'seq_wht_4_2_3_total_tax_amount': 300.0,
    'seq_wht_4_2_3_tax_amount': '300',
    'seq_wht_4_2_3_tax_amount_precision': '00',
    'seq_wht_4_2_4_date': '19/04/2565',
    'seq_wht_4_2_4_total_base_amount': 3000.0,
    'seq_wht_4_2_4_base_amount': '3,000',
    'seq_wht_4_2_4_base_amount_precision': '00',
    'seq_wht_4_2_4_total_tax_amount': 300.0,
    'seq_wht_4_2_4_tax_amount': '300',
    'seq_wht_4_2_4_tax_amount_precision': '00',
    'seq_wht_4_2_5_date': '19/04/2565',
    'seq_wht_4_2_5_total_base_amount': 3000.0,
    'seq_wht_4_2_5_base_amount': '3,000',
    'seq_wht_4_2_5_base_amount_precision': '00',
    'seq_wht_4_2_5_total_tax_amount': 300.0,
    'seq_wht_4_2_5_tax_amount': '300',
    'seq_wht_4_2_5_tax_amount_precision': '00',
    'seq_wht_5_date': '19/04/2565',
    'seq_wht_5_total_base_amount': 21000.0,
    'seq_wht_5_base_amount': '21,000',
    'seq_wht_5_base_amount_precision': '00',
    'seq_wht_5_total_tax_amount': 2100.0,
    'seq_wht_5_tax_amount': '2,100',
    'seq_wht_5_tax_amount_precision': '00',
    'seq_wht_6_date': '19/04/2565',
    'seq_wht_6_total_base_amount': 21000.0,
    'seq_wht_6_base_amount': '21,000',
    'seq_wht_6_base_amount_precision': '00',
    'seq_wht_6_total_tax_amount': 2100.0,
    'seq_wht_6_tax_amount': '2,100',
    'seq_wht_6_tax_amount_precision': '00'}

# Function update_group_data_line_wht

LINES_WHT = {
    'seq_wht_1_date': '',
    'total_base_amount': 0,
    'wht_total_base_amount': 0,
    'seq_wht_1_total_base_amount': 0,
    'seq_wht_1_base_amount': 0,
    'seq_wht_1_base_amount_precision': 0,
    'total_tax_amount': 0,
    'wht_total_base_amount_precision': 0,
    'seq_wht_1_total_tax_amount': 0,
    'seq_wht_1_tax_amount': 0,
    'seq_wht_1_tax_amount_precision': 0,
    'wht_total_tax_amount': 0,
    'th_wht_total_tax_amount': '',
}

UPDATE_GROUP_DATA = {
    'seq_wht_1_date': '19/04/2565',
    'total_base_amount': 3000.0,
    'wht_total_base_amount': '3,000',
    'seq_wht_1_total_base_amount': 3000.0,
    'seq_wht_1_base_amount': '3,000',
    'seq_wht_1_base_amount_precision': '00',
    'total_tax_amount': 300.0,
    'wht_total_base_amount_precision': '00',
    'seq_wht_1_total_tax_amount': 300.0,
    'seq_wht_1_tax_amount': '300',
    'seq_wht_1_tax_amount_precision': '00',
    'wht_total_tax_amount': '300',
    'th_wht_total_tax_amount': 'สามร้อยบาทถ้วน',
    'wht_total_tax_amount_precision': '00'}
