{
    'name': 'Kbt: Core Install',
    'summary': 'Core Install',
    'author': 'Kbt',
    'category': 'Hidden',
    'website': 'https://roots.tech',
    'version': '15.0.0.0.1',
    'license': 'LGPL-3',
    'depends': [
        'base_location',
        'base_location_geonames_import',
        'kbt_account_ext',
        'kbt_address_ext',
        'kbt_api_base',
        'kbt_approval',
        'kbt_business_type',
        'kbt_core_update',
        'kbt_delivery_api',
        'kbt_good_receipt_api',
        'kbt_journal_api',
        'kbt_partner_account_ext',
        'kbt_partner_api',
        'kbt_partner_ext',
        'kbt_payment_api',
        'kbt_purchase_api',
        'kbt_res_company',
        'kbt_sale_order_api',
        'kbt_stock_picking_ext',
        'os_disable_quick_create',
        'report_xlsx',
        'rts_api_base',
        'th_address'
    ]
}
