{
    'name': 'KBT Core Install',
    'summary': 'KBT Core Install',
    'author': 'KBT',
    'website': 'https://roots.tech',
    'version': '15.0.0.0.1',
    'depends': [
        'base_account_budget',
        'base_accounting_kit',
        'base_country_state_translatable',
        'base_location',
        'base_location_geonames_import',
        'beecy_account',
        'beecy_account_billing_note',
        'beecy_account_cheque',
        'beecy_account_discount',
        'beecy_account_discount_ext',
        'beecy_account_partner_bank_ext',
        'beecy_account_payment',
        'beecy_account_payment_ext',
        'beecy_account_purchase_ext',
        'beecy_account_sale',
        'beecy_account_tax',
        'beecy_account_wht',
        'beecy_base',
        'beecy_company_ext',
        'beecy_core_install',
        'beecy_core_update',
        'beecy_date_range_sequence',
        'beecy_font',
        'beecy_partner_attachment',
        'beecy_partner_ext',
        'beecy_partner_title',
        'beecy_reason',
        'beecy_sale_report',
        'beecy_web_report',
        'kbt_account_ext',
        'kbt_api_base',
        'kbt_business_type',
        'kbt_core_update',
        'kbt_delivery_api',
        'kbt_good_receipt_api',
        'kbt_journal_api',
        'kbt_partner_api',
        'kbt_payment_api',
        'kbt_purchase_api',
        'kbt_res_company',
        'kbt_sale_order_api',
        'kbt_stock_picking_ext',
        'os_disable_quick_create',
        'report_xlsx',
        'rts_api_base',
        'th_address'
    ]
}
