options = {
    'addon_path': ['additional-addons'],
    'depends': ['rts_api_base'],
    'exclude_dirs': [
        'base_account_budget',
        'base_accounting_kit',
        'base_country_state_translatable',
        'base_location',
        'base_location_geonames_import',
        'beecy_account',
        'beecy_account_billing_note',
        'beecy_account_cheque',
        'beecy_account_discount',
        'beecy_account_discount_ext',
        'beecy_account_partner_bank_ext',
        'beecy_account_payment',
        'beecy_account_payment_ext',
        'beecy_account_purchase_ext',
        'beecy_account_sale',
        'beecy_account_tax',
        'beecy_account_wht',
        'beecy_base',
        'beecy_company_ext',
        'beecy_core_install',
        'beecy_core_update',
        'beecy_date_range_sequence',
        'beecy_font',
        'beecy_partner_attachment',
        'beecy_partner_ext',
        'beecy_partner_title',
        'beecy_reason',
        'beecy_sale_report',
        'beecy_web_report'
    ]
}
